# fly.toml app configuration file generated for free-vps1012634734 on 2026-08-13T03:39:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'free-vps1012634734'
primary_region = 'sin'

[build]

[services]
  protocol = "tcp"
  internal_port = 22

  [[services.ports]]
    port = 2222

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
