# fly.toml app configuration file for free-vps1012634734

app = 'free-vps1012634734'
primary_region = 'sin'

[build]

# 1. SSH 服务端口映射 (内部 22 -> 外部 2222)
[[services]]
  protocol = "tcp"
  internal_port = 22

  [[services.ports]]
    port = 2222

# 2. 转换引擎服务端口映射 (内部 25500 -> 外部 25500)
[[services]]
  protocol = "tcp"
  internal_port = 25500

  [[services.ports]]
    port = 25500
    handlers = ["http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
