name: KeepAlive

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时自动运行一次（你也可以根据需要自行调整频率）
  workflow_dispatch:      # 支持在 Actions 页面手动点击运行

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Free-vps App
        run: |
          curl -I "https://edgetunnel-db-54x.pages.dev/sub?token=2212ba9a24e8ee2fe6d4b7576028a8ff"
